export { pool } from "./pool.js";
import { init } from "./schema.js";
import {
  getMaxLedger,
  getEventsCursor,
  upsertEvent,
  getEvents,
  getEvent,
  getWalletEvents,
  getContractTransactions,
  get24hVolume,
  getUpgradeHistory,
  getEventsForExport,
} from "./events.js";
import {
  getContractMeta,
  upsertContractMeta,
  getContractsForExport,
  updateCircuitBreakerStatus,
  getCircuitBreakerStatus,
  getMigrationStatus,
} from "./contracts.js";
import {
  registerVault,
  unregisterVault,
  getVaults,
  getVault,
  getActiveVaultIds,
  upsertVaultSnapshot,
  getVaultHistory,
  getTokenHolders,
  applyTransfer,
  applyMint,
  applyBurn,
} from "./vaults.js";
import {
  saveCursor,
  loadCursor,
  upsertRole,
  getRoles,
  query,
  addSourceVerification,
  getSourceVerifications,
  insertStateDiffs,
  getStateDiffs,
  upsertWasmBuildMetadata,
  getWasmBuildMetadata,
  upsertSubInvocations,
  getSubInvocationEdges,
} from "./admin.js";

export const db = {
  init,
  getMaxLedger,
  saveCursor,
  loadCursor,
  getEventsCursor,
  upsertEvent,
  getEvents,
  getEvent,
  getWalletEvents,
  getContractMeta,
  upsertContractMeta,
  getContractsForExport,
  getContractTransactions,
  get24hVolume,
  getUpgradeHistory,
  updateCircuitBreakerStatus,
  getCircuitBreakerStatus,
  getMigrationStatus,
  registerVault,
  unregisterVault,
  getVaults,
  getVault,
  getActiveVaultIds,
  upsertVaultSnapshot,
  getVaultHistory,
  upsertRole,
  getRoles,
  query,
  addSourceVerification,
  getSourceVerifications,
  insertStateDiffs,
  getStateDiffs,
  upsertWasmBuildMetadata,
  getWasmBuildMetadata,
  upsertSubInvocations,
  getSubInvocationEdges,
  getTokenHolders,
  applyTransfer,
  applyMint,
  applyBurn,
  getEventsForExport,
};
