declare namespace Express {
  interface Request {
    body: any;
    coldStorage?: {
      enabled: boolean;
      type: string;
      path?: string;
      ledgerSeq: number;
    };
    network: import('../profiles').NetworkName;
    networkProfile: import('../profiles').NetworkProfile;
    /** Unique ID for this HTTP request (correlation). */
    requestId: string;
    /** OpenTelemetry / B3 trace ID propagated from upstream or generated by OTel. */
    traceId: string;
    /** OpenTelemetry / B3 span ID of the root server span. */
    spanId: string;
  }
}
