import { NetworkName, NetworkProfile } from '../profiles';
import { ApiKeyContext } from '../middleware/apiKeyAuth';
import { TokenBucketResult } from '../middleware/tokenBucket';
import { Role, Tier } from '../auth/rbac';

declare module 'express-serve-static-core' {
  interface Request {
    body: any;
    coldStorage?: {
      enabled: boolean;
      type: string;
      path?: string;
      ledgerSeq: number;
    };
    network: NetworkName;
    networkProfile: NetworkProfile;
    requestId?: string;
    startedAt?: number;
    apiKey?: ApiKeyContext;
    rateLimitResult?: TokenBucketResult;
    user?: {
      id: string;
      address: string;
      role: Role;
      tier: Tier;
      sessionId: string;
      appId?: string;
    };
    network: import('../profiles').NetworkName;
    networkProfile: import('../profiles').NetworkProfile;
    /** Unique ID for this HTTP request (correlation). */
    requestId: string;
    /** OpenTelemetry / B3 trace ID propagated from upstream or generated by OTel. */
    traceId: string;
    /** OpenTelemetry / B3 span ID of the root server span. */
    spanId: string;
    /** Admin actor identity set by adminAuth middleware (freeze, audit routes). */
    actor?: string;
  }
}
