import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { asyncHandler } from '../middleware/asyncHandler';
import {
  extractWasmAbi,
  validateAbiCoverage,
  mergeCallSiteInference,
  CallSiteSample,
} from '../indexer/wasm-abi-extractor';
import { rpc } from '../indexer/rpc';
import { prismaRead, prismaWrite } from '../db';
import { getCachedAbi, setCachedAbi } from '../indexer/abi-cache';

export const abiExtractRouter = Router();

/**
 * GET /api/v1/abi-extract/:address
 * Extract ABI from WASM for any contract, with full inference pipeline.
 * Priority: manual override > on-chain spec > inferred > SEP-matched > generic
 */
abiExtractRouter.get(
  '/:address',
  asyncHandler(async (req: Request, res: Response) => {
    const { address } = req.params;

    // Manual ABI takes precedence
    const manual = await getCachedAbi(address);
    if (manual) {
      return res.json({ source: 'manual', abi: manual, address, autoGenerated: false });
    }

    let wasm: Buffer;
    try {
      wasm = await rpc.getContractWasmByContractId(address);
    } catch {
      return res.status(404).json({ error: 'Contract WASM not found', address });
    }

    // Fetch historical call samples for call-site inference
    const historicalCalls = await prismaRead.transaction.findMany({
      where: { contractAddress: address, functionName: { not: null } },
      select: {
        functionName: true,
        functionArgs: true,
        hash: true,
        ledgerSequence: true,
        status: true,
      },
      take: 200,
      orderBy: { ledgerSequence: 'desc' },
    });

    const callSamples: CallSiteSample[] = historicalCalls
      .filter((t) => t.functionName)
      .map((t) => ({
        functionName: t.functionName!,
        args: Array.isArray(t.functionArgs)
          ? (t.functionArgs as { type: string; value: unknown }[])
          : [],
        txHash: t.hash,
        ledgerSequence: t.ledgerSequence,
      }));

    const historicalCallsSimple = historicalCalls.map((t) => ({
      functionName: t.functionName ?? '',
      success: t.status === 'SUCCESS',
    }));

    let result = extractWasmAbi(wasm);
    result = mergeCallSiteInference(result, callSamples);
    const validation = validateAbiCoverage(result, historicalCallsSimple);

    // Cache the extracted ABI if high enough confidence
    if (result.functions.length > 0 && result.coverageScore >= 0.5) {
      const abiForCache = {
        functions: result.functions.map((f) => ({
          name: f.name,
          inputs: f.params.map((p) => ({ name: p.name, type: p.type })),
          outputs: [{ type: f.returns }],
          humanTemplate: f.doc,
        })),
      };
      await setCachedAbi(address, abiForCache).catch(() => null);
    }

    return res.json({
      address,
      source: result.source,
      autoGenerated: true,
      sepStandards: result.sepStandards,
      functions: result.functions,
      exports: result.exports.filter((e) => e.kind === 'function').slice(0, 50),
      imports: result.imports.filter((i) => i.kind === 'function').slice(0, 50),
      coverage: {
        score: result.coverageScore,
        percent: validation.coveragePercent,
        totalHistoricalCalls: validation.totalCalls,
        matchedCalls: validation.matchedCalls,
        falsePositives: validation.falsePositives.slice(0, 10),
        falseNegatives: validation.falseNegatives.slice(0, 10),
        confidenceByFunction: validation.confidenceByFunction,
      },
      warnings: result.warnings,
    });
  }),
);

/**
 * GET /api/v1/abi-extract/:address/sep
 * Detect which SEP standards a contract implements.
 */
abiExtractRouter.get(
  '/:address/sep',
  asyncHandler(async (req: Request, res: Response) => {
    const { address } = req.params;

    let wasm: Buffer;
    try {
      wasm = await rpc.getContractWasmByContractId(address);
    } catch {
      return res.status(404).json({ error: 'Contract WASM not found', address });
    }

    const result = extractWasmAbi(wasm);

    return res.json({
      address,
      sepStandards: result.sepStandards,
      isSEP41Token: result.sepStandards.includes('SEP-41'),
      isSEP10Auth: result.sepStandards.includes('SEP-10'),
      isSEP24Anchor: result.sepStandards.includes('SEP-24'),
      isSEP38RFQ: result.sepStandards.includes('SEP-38'),
      confidence: result.coverageScore,
    });
  }),
);

/**
 * GET /api/v1/abi-extract/:address/validate
 * Validate ABI coverage against historical transaction calls.
 */
abiExtractRouter.get(
  '/:address/validate',
  asyncHandler(async (req: Request, res: Response) => {
    const { address } = req.params;

    let wasm: Buffer;
    try {
      wasm = await rpc.getContractWasmByContractId(address);
    } catch {
      return res.status(404).json({ error: 'Contract WASM not found', address });
    }

    const result = extractWasmAbi(wasm);

    const historicalCalls = await prismaRead.transaction.findMany({
      where: { contractAddress: address, functionName: { not: null } },
      select: { functionName: true, status: true },
      take: 500,
    });

    const validation = validateAbiCoverage(
      result,
      historicalCalls.map((t) => ({
        functionName: t.functionName!,
        success: t.status === 'SUCCESS',
      })),
    );
    validation.contractAddress = address;

    return res.json(validation);
  }),
);

/**
 * POST /api/v1/abi-extract/community
 * Submit a community ABI correction for a contract.
 */
const communitySubmitSchema = z.object({
  address: z.string().min(1),
  functionName: z.string().min(1),
  params: z.array(z.object({ name: z.string(), type: z.string() })),
  returns: z.string(),
  contributor: z.string().optional(),
});

abiExtractRouter.post(
  '/community',
  asyncHandler(async (req: Request, res: Response) => {
    const parsed = communitySubmitSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

    const { address, functionName, params, returns, contributor } = parsed.data;

    const existing = await getCachedAbi(address);
    const functions = existing?.functions ?? [];

    const idx = functions.findIndex((f) => f.name === functionName);
    const updated = {
      name: functionName,
      inputs: params,
      outputs: [{ type: returns }],
    };

    if (idx >= 0) functions[idx] = updated;
    else functions.push(updated);

    await setCachedAbi(address, { functions });

    await prismaWrite.contract.upsert({
      where: { address },
      create: { address, abi: { functions } as object },
      update: { abi: { functions } as object },
    });

    return res.json({
      address,
      functionName,
      updated: true,
      contributor: contributor ?? 'anonymous',
    });
  }),
);

/**
 * GET /api/v1/abi-extract/:address/upgrade-check
 * Check if the ABI changed after a WASM upgrade.
 */
abiExtractRouter.get(
  '/:address/upgrade-check',
  asyncHandler(async (req: Request, res: Response) => {
    const { address } = req.params;

    const upgrades = await prismaRead.wasmUpgradeHistory.findMany({
      where: { contractAddress: address },
      orderBy: { ledgerSequence: 'desc' },
      take: 2,
    });

    if (upgrades.length < 2) {
      return res.json({ address, hasUpgrade: false, message: 'Less than 2 WASM versions found' });
    }

    let currentWasm: Buffer;
    try {
      currentWasm = await rpc.getContractWasmByContractId(address);
    } catch {
      return res.status(404).json({ error: 'Current WASM not found', address });
    }

    const current = extractWasmAbi(currentWasm);
    const currentNames = new Set(current.functions.map((f) => f.name));

    const previousNames = new Set<string>();
    const cached = await getCachedAbi(address);
    if (cached) cached.functions.forEach((f) => previousNames.add(f.name));

    const added = [...currentNames].filter((n) => !previousNames.has(n));
    const removed = [...previousNames].filter((n) => !currentNames.has(n));

    return res.json({
      address,
      hasUpgrade: upgrades.length >= 2,
      lastUpgradeLedger: upgrades[0].ledgerSequence,
      abiChanged: added.length > 0 || removed.length > 0,
      addedFunctions: added,
      removedFunctions: removed,
      currentFunctionCount: currentNames.size,
      sepStandards: current.sepStandards,
    });
  }),
);
