import { Router } from 'express';
import { transactionRouter } from './transactions';
import { eventRouter } from './events';
import { contractRouter } from './contracts';
import { walletRouter } from './wallets';
import { tokenRouter } from './tokens';
import { authorizationRouter } from './authorizations';
import { renderRouter } from './render';
import { simulateRouter } from './simulate';
import { verifyRouter } from './verify';
import { dexRouter } from './dex';
import { protocolRouter } from './protocol';
import { nftRouter } from './nft';
import { alertsRouter } from './alerts';
import { assetsRouter } from './assets';
import { sseRouter } from './sse';
import { graphRouter } from './graph';
import { virtualListRouter } from './virtualList';

export const router = Router();

router.use('/transactions', transactionRouter);
router.use('/events', eventRouter);
router.use('/contracts', contractRouter);
router.use('/wallets', walletRouter);
router.use('/tokens', tokenRouter);
router.use('/authorizations', authorizationRouter);
router.use('/render', renderRouter);
router.use('/simulate', simulateRouter);
router.use('/verify', verifyRouter);
router.use('/dex', dexRouter);
router.use('/protocol', protocolRouter);
router.use('/nft', nftRouter);
router.use('/alerts', alertsRouter);
router.use('/assets', assetsRouter);
router.use('/sse', sseRouter);
router.use('/graph', graphRouter);
router.use('/virtual-list', virtualListRouter);
